name: Generate Schedule JSON

on:
  push:
    paths:
      - "public/classes.csv" # Trigger the workflow when classes.csv is updated
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Match your desired Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install asyncpg

      # Step 4: Set up environment variables
      - name: Set up environment variables
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      # Get current working directory
      - name: Get current working directory
        run: pwd

      # Step 5: Run the Python script
      - name: Generate schedule JSON
        run: python scripts/generate_schedule.py

      # Step 6: Configure Git for committing changes
      - name: Configure Git
        run: |
          git config user.name "Taha Parker via GitHub Actions"
          git config user.email "98612931+tahayparker@users.noreply.github.com"
      # Step 7: Commit the updated JSON file to the root directory
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update scheduleData.json triggered by classes.csv update"
          file_pattern: 'scheduleData.json'

      # Step 8: Push changes back to the repository
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}