name: Update Timetable Data

on:
  schedule:
    # Run every day at 0000 UTC+4
    - cron: '0 16 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-timetable:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the last 2 commits to compare changes
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 cloudscraper asyncpg

      - name: Set up environment variables
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Generate new timetable data
        run: python scripts/scrape_timetable.py --output public/classes.csv
      
      - name: Check for CSV changes
        id: check_changes
        run: |
          if git diff --quiet HEAD^ HEAD public/classes.csv; then
            echo "No changes in CSV file"
            echo "csv_changed=false" >> $GITHUB_OUTPUT
          else
            echo "CSV file has changed"
            echo "csv_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Delete debug files
        run: rm -rf debug_page.html

      - name: Commit and push CSV changes
        if: steps.check_changes.outputs.csv_changed == 'true'
        run: |
          git config user.name "Taha Parker via GitHub Actions"
          git config user.email "98612931+tahayparker@users.noreply.github.com"
          git add public/classes.csv
          git commit -m "Update timetable CSV data [skip ci]"
          git push

      - name: Initialize the DB
        if: steps.check_changes.outputs.csv_changed == 'true'
        run: curl -X POST https://vacansee.vercel.app/api/initdb

      - name: Check for JSON file and generate if needed
        id: check_json
        run: |
          if [ ! -f public/scheduleData.json ] || [ "${{ steps.check_changes.outputs.csv_changed }}" == "true" ]; then
            echo "JSON file does not exist or CSV changed, will generate it"
            echo "should_generate=true" >> $GITHUB_OUTPUT
            python scripts/generate_schedule.py
          else
            echo "JSON file exists and no CSV changes"
            echo "should_generate=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Commit and push JSON changes
        if: steps.check_json.outputs.should_generate == 'true'
        run: |
          git config user.name "Taha Parker via GitHub Actions"
          git config user.email "98612931+tahayparker@users.noreply.github.com"
          git add -A
          git commit -m "Update timetable JSON data [skip ci]"
          git push
